emmaa/model.py, emmaa/priors/__init__.py, emmaa/priors/cancer_prior.py, models/aml/config.yaml, models/brca/config.yaml, models/luad/config.yaml, models/paad/config.yaml, models/prad/config.yaml, models/skcm/config.yaml, scripts/priors_from_muts.py
This PR enhances the format of the model configs to use SearchTerm objects instead of just a simple string. This allows keeping track of the type, grounding and canonical name of prior terms in addition to actual search strings.
=> Prior SearchTerm object model

emmaa/model.py, emmaa/statements.py, scripts/generate_simple_model_test.py
This PR adds json upload capabilities to the emmaa code. With models uploaded as jsons, they are more accessible by client side javascript.
Specific updates:
- Adds the method `to_json()` in the  `EmmaaStatement` class, allowing `indra.statements.smts_to_json` to be used on the `EmmaaStatement` class.
- Upload of models as jsons alongside pickles in `emmaa/model.py`
- Upload of test model config as both yaml and json in `scripts/generate_simple_model_test.py`
=> S3 json upload

emmaa/aws_lambda/script.py, emmaa/aws_lambda/update.py
Remove all dependency on `util.py` from the lambda script, and correspondingly from the files uploaded in `update.py`. This prevents unresolvable dependencies from creeping in through `util.py`.
=> Fix the model testing lambda framework

.gitignore, emmaa/aws_lambda_functions/analyze_changes_on_s3.py, emmaa/aws_lambda_functions/model_updates.py, emmaa/model.py, emmaa/model_tests.py, emmaa/tests/test_model_tests.py
This PR optimizes the model test structure and running time. A new class ModelManager has been added to store all attributes of a model together and generate them only once. 
Changes to the test:
- PySB model, model entities, and model checker are generated once at instanciation of ModelManager.
- After applicable tests are added, an influence map is generated once for all tests.
- Tests are now run for a list of applicable tests.
- TestManager takes a list of ModelManager objects now instead of list of EmmaaModels (every ModelManager has an EmmaaModel along with other attributes).
Suggestion: I also want to make test entities be generated only once at instantiation. To do that we need to reload small_corpus_tests.pkl to s3 with the updated class definition. I can do that if everything …
=> Optimize model test

emmaa/analyze_tests_results.py, emmaa/aws_lambda_functions/analyze_changes_on_s3.py, emmaa/model.py, emmaa/model_tests.py, emmaa/tests/test_model_tests.py, emmaa/util.py, scripts/get_model_test_stats.py, scripts/run_model_tests_from_s3.py
This PR generates model and test statistics for EMMAA dashboard. This step will be executed after each test run and it will upload additional JSON file to S3. The following statistics is generated:
- Model Summary: 
-- name
-- number of statements
-- statement types distribution
-- agents distribution
-- statements (hashes) with evidence count
-- English assembled statements mapped to hashes
- Test Summary:
-- number of applied tests
-- number of passed tests
-- ratio of passed tests over total applied
-- English descriptions of tests mapped to hashes
-- hashes of passed tests
-- English descriptions of found paths mapped to test hashes
- Model Delta between two latest rounds:
-- number of statements
-- actual added and removed statements (English)
- Test Delta between two latest round: …
=> Statistic for EMMAA dashboard

emmaa/model.py, emmaa/model_tests.py
This PR adds a method get_assembled_entities() to EmmaaModel class. The assembled entities are then used to check applicability of a test to a model. I also set default value of belief_cutoff to None and used 0.8 value only when calling run_model_tests_from_s3 function.
=> Assembled entities

emmaa/analyze_tests_results.py
This PR adds dates to the stats to be used in timeseries charts on the dashboard. As we at the moment have 2 json files without dates, I'm manually inserting first 2 values.
=> Add dates to stats

emmaa/model_tests.py
Save ModelManager to results folder instead of models folder to avoid AWS Batch jobs loop
=> Save model manager to results folder

dashboard/emmaaFunctions.js, doc/requirements.txt, emmaa/model.py, emmaa/model_tests.py, emmaa/tests/test_model_tests.py, scripts/emmaa_model_from_stmts.py, scripts/generate_simple_model_test.py, scripts/priors_from_muts.py, scripts/upload_to_s3.py, setup.py
This PR removes the YAML configuration approach and replaces it with JSON. The new JSON configuration contains the following entries:
- search_terms (pre-existing): a list of SearchTerm objects serialized into JSON
- name (pre-existing): the code name of the model, e.g. "aml"
- human_readable_name (new): the display name used for the model
- assembly (new): a dict of assembly configuration parameters including
- belief_cutoff
- filter_ungrounded
- filter_direct
- mechanism_linking
- ndex (pre-existing)
- network: the ID of the NDEx network for the model
Note that this PR does not remove the use of model_meta from the JS and REST API code, these will need to be done by @kkaris and @pagreene as a follow up to this. Once those changes are in place, we can delete the config.yaml files and the …
=> Model configuration with JSON

.travis.yml, doc/modules/priors.rst, emmaa/model.py, emmaa/priors/__init__.py, emmaa/priors/gene_list_prior.py, emmaa/tests/test_db.py, emmaa/tests/test_gene_list_prior.py, scripts/build_rasmachine_prior.py, scripts/priors_from_muts.py, scripts/run_model_update.py
This PR implements a new GeneListPrior class that takes a list of genes, and generates an initial model that it uploads to S3 (along with a config.json) and NDEx. 
The PR also fixes a bug in `emmaa.model` related to eliminating statement copies. Note that this PR also differentiates `upload_to_ndex` (meant for first time upload) from `update_to_ndex` (meant for updating an existing network).
=> Starting a new model based on a list of genes

emmaa/model.py, emmaa/model_tests.py
This PR adds a new `test` key to config.json that allows setting parameters for various kinds of model tests, for now handling `statement_checking`.
=> Handle test configuration from config.json

doc/modules/answer_queries.rst, doc/modules/index.rst, doc/modules/test_analysis.rst, emmaa/analyze_tests_results.py, emmaa/model_tests.py, emmaa/tests/test_model_tests.py
This PR adds two missing modules to the documentation, and makes running registered queries optional to make the failing test pass.
=> Improve documentation and fix tests

emmaa/answer_queries.py, emmaa/db/manager.py, emmaa_service/api.py
Fix queries and query registration. Queries can now be registered, and registered queries are now displayed when the query page is loaded. This PR also adds some logging messages to the db manager and the api.
=> Fix query registration

README.md, buildspec.yml
This PR improves the installation instructions in the README and adds a push to Dockerhub in buildspec.yml.
=> Push to Dockerhub when building image

emmaa/analyze_tests_results.py
This PR fixes an occasional KeyError in model tests stats generating process. The error occurred in cases when the path was found, but its length exceeded the maximum allowed length.
=> Fix KeyError

dashboard/emmaaFunctions.js
This PR resolves a bug were the basic info of the rasmachine model was not loaded because it was not in a hard coded list of models in `emmaaFunctions.js`.
=> Rasmachine bug fix

emmaa/db/manager.py
Allow either EmmaaTable objects or strings as elements of `tables` for both `create_tables` and `drop_tables`. Also add some more doc string.
=> Standardize interface for drop and create methods.

emmaa_service/api.py
When using gunicorn, set `GLOBAL_PRELOAD` to `True`, and the caches will be filled whenever the file is loaded.
=> Include global optional cache load.

dashboard/emmaaFunctions.js
This PR fixes an issue were linkouts from pre-generated strings in the new json structure did not have the right attribute added to them.
=> Fix linkout

emmaa/model.py, emmaa/tests/test_model.py
This PR adds a new assembly option that allows controlling how the new information collected at each update is handled upon assembly: the two options are prior_one and prior_all (or no filtering).
=> Add assembly option to filter by relevance

emmaa/analyze_tests_results.py
This PR changes incorrect classification of tests as passing or failing from result.paths to result.path_found. This change will ensure tests for which the path exceeds the maximum length, will be considered passing. We can expect an increase in percentage of tests passed due to this change.
=> Fix incorrect classification of tests with MAX_PATH_LENGTH_EXCEEDED

emmaa/db/manager.py, emmaa/tests/test_db.py
Return only the latest version of each result in a query. In the future, it would be good to parametrize this in some way that would allow the user to dig into the older results and see how they may have changed over time, but for now this is simply applied to all the results that are retrieved from emmaa's database.
=> Return only the latest results to a query

dashboard/emmaaFunctions.js, dashboard/index.html, dashboard/model.html, dashboard/query.html, emmaa/answer_queries.py
This PR makes a some UI improvements:
- The landing page model cards are now centered on the page
- Line charts now have a zoom capability by scrolling while the pointer hovers on the graph
- Links to the indra db now also opens in a new tab by default for old queries
- The top navbar is now sticky for all pages
_Links to other emmaa pages are **not** opened in new tabs._
=> Improve charts and ui

.gitignore, emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/model_tests.py, emmaa/queries.py, emmaa/tests/path_property_query.json, emmaa/tests/test_answer_queries.py, emmaa/tests/test_db.py, emmaa/tests/test_model_tests.py, emmaa/tests/test_queries.py, emmaa_service/api.py, setup.py
This PR makes changes to query answering process.
- New parent class Query and four child classes for different types of queries are created. For now only PathProperty class is implemented.
- API creates a Query object from a simple form ("typeSelection", "objectSelection", "subjectSelection") using Grounding service.
- A Query object can be passed to QueryManager class that can interact with the DB Manager and ModelManager, answer immediate and registered queries (using relevant methods of ModelManager), save and retrieve queries and results to a database, find delta between query results and produce reports in either string or html format.
- The easiest way to get a report for delta in query results is to use either `qm.get_user_query_delta(user_email, filename, report_format)` # …
=> Query Refactor

emmaa/model_tests.py
This PR fixes the bug of delta reporting in logs. The delta is found by comparing the hashes of new result and previous result. The issue here was that hashes are generated as integers and are automatically converted to string when saved to db. As a result, integers (hash of new result before saving to db) were compared to string (hash of previous result from db) and we got false positive delta. The PR makes hashes to always be strings and avoid type difference.
=> Fix query result delta bug

.travis.yml, emmaa/answer_queries.py, emmaa/db/constructors.py, emmaa/model_tests.py, emmaa/resources/default_db_config.ini, emmaa/tests/test_answer_queries.py, emmaa/tests/test_db.py, emmaa/tests/test_model_tests.py
To add extra distance between the testing and primary databases, and also to resolve issues of conflicting access to a shared resource, use the local postgres database provided by Travis to test. This will require local tests to create a local database for testing (detailed instructions could perhaps be included in a later PR).
=> Change over to using a travis db

emmaa/tests/README.md
This PR simple adds a README to the `tests` directory with instructions on how to setup the tests database on your local machine. Note that this makes no assumptions about the version of the postgres database, as the EMMAA project is not version specific, however others of our projects (specifically `indra_db`) that require a local test database _are_ version specific.
=> Add documentation for test db

.gitignore, emmaa/answer_queries.py, emmaa/model_tests.py, emmaa/tests/test_answer_queries.py, emmaa/tests/test_queries.py, emmaa_service/api.py
This PR changes how GroundingError is handled on the API side. Because of the refactoring made in #79, GroundingError will be raised earlier at the stage of creating a query in `_make_query` from a user form (it used to happen at the level of answering the query). I also parameterized using the Grounding service in this function which makes it easier to run and test locally.
=> Improvements to Query Refactor #79 

dashboard/emmaaFunctions.js
This PR fixes a bug in which the prefix for listing objects on S3 was too general, so that the resulting list of objects was longer than the allowed maximum value of 1000 for the list returned to the client. This resulted in some model files not being listed as they were outside the allowed range of the returned list, which caused the function that gets the date of the latest model to fail.
The PR also adds the `marm_model` to the list of models and simplifies the creation of the keyed array in `getModels`.
=> Limit s3 listing

emmaa/queries.py
This PR fixes the KeyError when submitting queries by using the correct json structure.
=> Use new grounding service json structure

emmaa/analyze_tests_results.py, emmaa/model.py
Recalculate hashes every time we need them to avoid False positive in new statements/tests (that would happen if we use old and new hashes together).
=> Refresh hash

emmaa/model.py, emmaa/queries.py
This PR adds 2 unrelated improvements. First, the search of Elsevier for food insecurity model is limited to 5 results per search term. This is a temporary solution until we improve the search quality. I also changed "conflict" to "armed conflict" and "market" to "food market" in config file on S3. Second commit in this PR is updating the way grounding service is called - from environment variable (now has working link) rather than explicitly providing (outdated) link in the code.
=> Improvements

emmaa/model_tests.py
This PR updates the model testing to use new PysbModelChecker class, has to be merged together with https://github.com/sorgerlab/indra/pull/943
=> Use PysbModelChecker for tests

emmaa/aws_lambda_functions/model_updates.py, emmaa/aws_lambda_functions/update_pipeline.py, scripts/run_model_update.py
This PR changes the model update pipeline. Instead of having one Batch job to update all models, each model will have its own job and instead of hardcoding the list of models for daily update, this option is provided in config files for each model. The process involves 2 Lambda functions:
- `emmaa-update-pipeline` gets a list of all existing models from S3 and checks their config files for run_daily_update parameter. If it's set to 'True', the function calls a different Lambda function to update this model.
- `emmaa-model-update` gets a model name inside the 'event' parameter and starts a batch job with a script `run_model_update` which is now parameterized to take model name as a parameter and only update one model. It will be also possible to trigger this function directly for one model …
=> Model update jobs

dashboard/emmaaFunctions.js
This PR fixes a bug where too many objects were returned from [s3.ListObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) (max is 1000), causing the last model, SKCM, to not get all its latest files listed.
The bug was solved by sending a more precise prefix the to the function calling the ListObjects API.
=> List s3 objects with higher precision

emmaa/tests/test_api_functions.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/static/queryFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/query_template.html
This PR moves a lot of the JavaScript functionality to the Python back end, thanks to jinja2 templates.
There is still a need for JavaScript to carry out certain functions, namely:
- Taking care of POSTing to endpoint
- Displaying graphics of the data
The JavaScript code handling this remains in the affected files.
=> Move JS functionality to Python back end

emmaa/model.py
This PR adds a waiting period between calls to Elsevier API to avoid getting status code 429.
=> Sleep between Elsevier requests

emmaa/model.py
This small PR increases sleep time between Pubmed client requests from 0.5 to 1 analogously to Elsevier client calls. Reviewing some Batch job logs showed that 0.5 is not enough.
=> Increase sleep time for Pubmed client

.travis.yml, emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/tests/test_answer_queries.py, emmaa/tests/test_db.py, emmaa/tests/test_queries.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/static/queryFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/query_template.html, setup.py
This PR sets up the framework needed for being able to login to the emmaa services. All pages are still available to the user without being logged in. Instead, certain capabilities are blocked/not visible to an anonymous user.
The most notable changes in the UI are:
- An added login button on the navbar
- Subscribed queries are now shown on a user basis, provided that the user is logged in
- If a user tries to subscribe to a query without being logged in, they are prompted to log in
Changes on the back-end include:
- Add a new column, 'count', to the UserQuery table that stores how many times a user has made a certain query.
- All handling of users that was previously not done is now handled.
**_The merging of this PR must also coincide with an update of the tables_**
=> Add login capabilities

emmaa/tests/test_reactome_prior.py
This PR updates tests for the reactome prior which were no longer passing due to changes in results returned by the reactome REST API. For most tests, the failures were due to changes in the reactome hierarchy. Some pathways and entities that were included in tests were recently split into multiple pathways and entities respectively, causing assertions to fail. 
There is still a mystery as to why the prior generated from only the gene KRAS has shrank. I suspect this is likely due to changes in the mapping of Uniprot IDs. The priors generated from multiple genes still appear to be of reasonable size and content. For now it appears best to continue mapping genes to reactome IDs based on Uniprot ID. The priors generated when mapping by HGNC symbol are very large; a prior with over 6000 genes …
=> Reactome fix

emmaa/analyze_tests_results.py, emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/model_tests.py, emmaa/tests/test_answer_queries.py, emmaa_service/api.py, emmaa_service/static/queryFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/index_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/query_template.html, emmaa_service/templates/tests_template.html
This PR makes use of ui_util web templates for queries page similarly to tests page.
Back end changes
-------------------
- Query results format is changed to the same format as in test results
- Adding some functionality to easily retrieve results from database with query hashes
Front end changes
-------------------
- Query page is switched to using templates
- Query page now shows high level grid like (pass/fail/NA) table of results for recent and subscribed queries
- Pass/fail/NA signs link out to detailed query result page with detailed paths and explanations
- Only query hashes are stored in session and used to retrieve results from the database
=> Query page restructure

emmaa_service/api.py
This PR changes the sorting of the test results tables. The rows where all the tests are not applicable are removed. The sorting is then done primarily on the count of passed tests, then on model types (PySB, PyBEL, Signed Graph then Unsigned Graph) with a ranking of passing test ranking higher than a failing test and a failing test ranking ranking higher than a not applicable test.
=> Test table sorting

emmaa/model.py, emmaa/model_tests.py
This PR separates query settings from test settings for EMMAA model checking. The query settings can be configured in config.json for each model or will use the default values if not provided. Default values currently are: max_path_length = 5 and max_paths = 5 (vs test settings where max_paths = 1). Query and test settings can be generic or model type specific. Syntax to add them in config.json:
`"query": {"statement_checking" : {"max_path_length" : 5, "max_paths": 5,
"pybel": {"max_path_length" : 10, "max_paths": 5}}}`
In this example settings for pybel will override generic settings, but generic will be used for all other model types.
=> Query settings

emmaa/model.py, emmaa/tests/test_api_functions.py, emmaa/tests/test_model.py, emmaa/tests/test_reactome_prior.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/index_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/query_template.html, emmaa_service/templates/tests_template.html
This PR adds 'time travel' functionality to EMMAA dashboard. User can click on the earlier point on any of three time graphs and be redirected to the dashboard displaying statistics for that date. This functionality is supported on model/tests page and on detailed test results page. It is possible to go back to present by clicking the button on top of the page. This PR also moves some more generic useful functions from emmaa_service/api.py to emmaa/model.py and adds more tests. 
Changes are deployed on EMMAA dev machine.
This PR depends on https://github.com/indralab/ui_util/pull/4
=> Time Machine

emmaa_service/static/queryFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/query_template.html
This PR fixes a bug that prevented subscription to dynamic queries because the element ID of "Subscribe" checkbox was not unique (it was only possible to subscribe if the checkbox was checked on static tab)
=> Fix subscribing to dynamic query bug

emmaa/answer_queries.py
This PR updates load_model_manager_from_cache function to check if the cached version of the ModelManager is also the latest available on S3 and load a new one otherwise.
=> Reload ModelManager

emmaa/analyze_tests_results.py, emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/model.py, emmaa/model_tests.py, emmaa/tests/test_s3.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/tests_template.html
This PR enables navigating to previous or next result when on detailed test/query result page. Front end changes depend on https://github.com/indralab/ui_util/pull/6. On the back end, few changes were made to api, util and db manager to enable finding previous/next results for both tests (from s3) and queries (from db). This PR also adds test_corpus as a url parameter on the detailed test page (it was previously only used on the test page with all test results) which enables browsing individual test results for any test corpora (it was only possible for default test corpus before).
Additionally, this PR makes changes to StatsGenerator methods for loading previous round files - backwards compatibility to load files with older filenames is removed and additional checks are added to make …
=> Update to detailed results page and loading previous files

emmaa/answer_queries.py, emmaa/db/manager.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js
This PR patches some small issues that came up after merging #126 and #128.
Main changes:
- Links to the detailed query results from emails will now work with the update for paging
- `db.get_results_from_hashes()` returns unique results
- Model page links from query page are fixed
- Several pages now have default values if query parameters are missing
=> Query link patch

doc/requirements.txt, emmaa/queries.py, emmaa/tests/test_queries.py, emmaa_service/api.py, setup.py
This PR removes some of the deprecated grounding approaches in the code and replaces them with using `gilda` assuming it is installed as a Python package (i.e., not used as a web service).
=> Clean up grounding and use Gilda as a package

emmaa/model.py
This PR adds a custom filter function to filter Eidos statements with ungrounded agents. The filtering depends on merging https://github.com/sorgerlab/indra/pull/1087 (to consider agents with TEXT_NORM only as ungrounded)
=> Filter ungrounded Eidos stmts

emmaa/answer_queries.py, emmaa/model_tests.py, emmaa/queries.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/maintenance.html, emmaa_service/templates/tests_template.html
This PR makes two substantial updates:
**Endpoint normalization and nginx compatibility:**
- All trailing slashes have been removed in endpoints and links
- A static "down for maintenance" html page has been added
- nginx has been set up to redirect old links that go to now extinct endpoints (outside code of PR)
**badge updates**
All statements and statement evidence pages now display the following badges:
- Evidence count
- Link to statement json
- Count of paths the statement is a part of
- Count of correct/incorrect curations in the scope and outside of the scope of current model
- Evidence level badges showing correct/incorrect curations.
This PR depends on the following PRs being merged: https://github.com/sorgerlab/indra/pull/1086, https://github.com/indralab/ui_util/pull/8, …
=> Endpoint normalization and badges customization

emmaa/model.py, emmaa/readers/db_client_reader.py, emmaa/tests/test_answer_queries.py
This PR allows EMMAA models to get extended with statements from BioRxiv and get new statements from more than one literature source. Since both PMID and DOI based statements are sourced from INDRA DB, the generalized function is created for getting statements from INDRA DB and ID specific functions call it with different parameters. To get statements from multiple literature sources, a list of sources and a corresponding list of users need to be provided in model config, e.g. 
`config['reading'] = {'literature_source': ['pubmed', 'biorxiv'], 'reader': ['indra_db_pmid', 'indra_db_doi']}`
=> Get new readings from BioRxiv

emmaa/model.py
This PR fixes an issue where a string was used as a search term, but downstream code expects a SearchTerm object to be used.
=> Add SearchTerm object for biorxiv collections

emmaa/model_tests.py, emmaa_service/api.py
This PR makes several changes:
- Pass correct expected format of curation dict into _format_evidence_text
- Fix issue when evidence for non-curated statements were not loaded
- Handle issue of creating artificial Conversion statements from groups
- Update the path count badge
=> Minor updates and fixes

emmaa/model_tests.py, emmaa_service/api.py
This PR makes it easier to get latest assembled statements of a given model in multiple ways:
- At assembly time, the assembled statements will be dumped into a constantly updated 'latest_statements_{model_name}.json' file to be found easily (first file in S3 directory) and a timestamped file for keeping track of changes
- Download statements button on all statements page will download (if available) the file called 'latest_statements_{model_name}.json' instead of time-stamped one
- New endpoint ('/latest_statements/<model>') allows to get statement jsons and the link to latest file programmatically through API request
=> Assembled statements

emmaa/analyze_tests_results.py, emmaa/model.py, emmaa/model_tests.py, emmaa/tests/test_s3.py, emmaa_service/api.py, emmaa_service/templates/model_template.html
This PR adds descriptions of test corpora that should be included in test pickle files and it will be propagated to stats files and displayed on test page. Model based tests are configured to autogenerate and include the descriptions at update. Manual tests pickles should be updated to contain a dictionary with keys 'description' and 'tests'. Updates are backward-compatible.
UPD: The test dictionary is updated to have the keys 'tests' (mapped to a list of tests) and 'test_data' (mapped to a dictionary containing any information about test corpus such as 'description').
=> Test descriptions

Dockerfile
This PR pulls the latest INDRA code when EMMAA docker is built.
=> Checkout latest INDRA code in docker

emmaa/model.py, emmaa/tests/test_s3.py, emmaa/util.py, emmaa_service/api.py
This PR replaces loading the model manager pickles with loading assembled stmts jsons when displaying statement evidence on model page and all statements page. These files are smaller and faster to load.
=> Load assembled statements for evidence browsing

emmaa/analyze_tests_results.py, emmaa/tests/test_stats.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/model_template.html
This PR adds the bar chart displaying the distribution of evidence counts in model statements by knowledge source. The counts are stored in stats model summary. New statistics will be displayed after daily stats jobs are run, but the service can be updated any time (front end is backward compatible).
=> Show knowledge sources

emmaa/model.py, emmaa/model_tests.py, emmaa/priors/cancer_prior.py, emmaa/priors/gene_list_prior.py, emmaa/priors/reactome_prior.py, emmaa/readers/aws_reader.py, emmaa/tests/test_answer_queries.py, emmaa/tests/test_gene_list_prior.py, emmaa/tests/test_lambda.py, emmaa/tests/test_reactome_prior.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/evidence_template.html, emmaa_service/templates/model_template.html
This PR introduces several changes:
-`get_assembled_statements` function is parameterized to take `date` argument to allow loading statements for different date
- Evidence page and all statements page URLs also include date parameter which determines which state of the model to load
- This allows browsing evidences for statements that were removed from the model
- Assembled statements are saved in two formats: JSON and JSONL
- To fix some failing tests, the code requiring loading statements from TAS was also updated here (in gene_list_prior, reactome_prior and cancer_prior and corresponding tests)
This PR should be merged together with https://github.com/indralab/ui_util/pull/10
=> Save load stmts

emmaa/model.py, emmaa/model_tests.py, emmaa/tests/test_s3.py, emmaa/util.py
This PR fixes a problem with pickling large models by removing both raw and assembled statements from ModelManager object before pickling and upgrading the pickle protocol to highest available.
=> Fixing ModelManager pickling

emmaa/answer_queries.py, emmaa/model_tests.py, emmaa/readers/db_client_reader.py, emmaa/util.py, emmaa_service/api.py, setup.py
This PR adds the following changes:
- Saving paths information in JSONL format at each test run
- Fixing a few email notification and query configuration bugs
- Changing the way assembled statements are zipped/saved/loaded in the manner that doesn't require writing to disc
=> Save paths and fix issues

emmaa/analyze_tests_results.py, emmaa/answer_queries.py, emmaa/aws_lambda_functions/after_update.py, emmaa/tests/test_stats.py, emmaa/util.py, emmaa_service/api.py, scripts/tweet_deltas.py, setup.py
This PR enables tweeting of EMMAA model updates. There are currently three possible tweet messages: about number of new statements, number of new applied tests, and number of new passed tests (per specific model type). The tweet message  is going to be logged in model stats and test stats logs for all models if there's delta detected. To switch on the tweeting for a model, 'twitter' parameter has to be added to the config. Credentials should be stored as SSM parameters. Some code from Indra twitter_client.py was moved to this PR.
=> Individual models tweets

emmaa/model.py
This PR allows to modify file names in the config file to enable loading different custom sets of statements for COVID19 model.
=> Configuring extra statements files for COVID19 model

emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/db/schema.py, emmaa/tests/README.md, emmaa/tests/db_setup.py, emmaa/tests/test_answer_queries.py, emmaa/tests/test_db.py, emmaa/tests/test_s3.py, setup.py
This PR updates query delta related code. Major changes:
- Removing old unused code, simplifying, refactoring, cleaning, updating code in `answer_queries.py`
- Moving the step of deriving data to database manager from query manager.
- Switching from "delta between last two results" to "new result never seen before".
- Adding two more columns in database Result to keep a set of all hashes of previous result and delta.
- Utilizing nosetests fixtures in a new setup for tests using database - creating/dropping test database.
- Adding more tests in test_answer_queries and test_db for new and old untested code.
- Propagating query delta information to front end for highlighting (works with https://github.com/indralab/ui_util/pull/11)
=> Query delta

emmaa/filter_functions.py, emmaa/model_tests.py
This PR integrates changes proposed in https://github.com/sorgerlab/indra/pull/1179 into EMMAA model testing pipeline. To add constraints to a specific model+test corpus combination, the function has to be defined as a filter function and its name has to be added to model config file. A sample function is defined as a part of this PR, that filters out nodes grounded to CHEBI, MESH and GO.
=> Path constraint in EMMAA tests

emmaa/filter_functions.py
Allow agents that would be otherwise filtered if they also have HMDB groundings.
=> Update filter function

emmaa/model_tests.py
This PR propagates human readable name to test corpus based on models. This name is used in tweets. For example, it would replace `nf_tests` with `Neurofibromatosis model test corpus`
=> Put human readale name to model based tests

emmaa/analyze_tests_results.py, emmaa/model.py, emmaa/tests/previous_model_stats.json, emmaa/tests/test_model.py, emmaa/tests/test_stats.py
This PR adds the data about papers processed into the pipeline. EmmaaModel is updated to keep track of all papers processed for the current round. ModelRound and ModelStatsGenerator are updated to report about both papers used at the reading level and papers from which the evidences of assembled statements are extracted. This PR should be merged together with https://github.com/indralab/covid-19/pull/9
=> Paper data

emmaa_service/api.py
This PR goes hand-in-hand with https://github.com/indralab/indra_db/pull/143 and https://github.com/sorgerlab/indra/pull/1192, in which the results of `get_curations` are returned as JSON instead of database-session-leaking objects.
=> Curation JSON-ify

emmaa/util.py
This PR fixes a bug that was causing loading of earlier models instead of latest. `iter_s3_keys` function that handles the issue of truncated list of files in INDRA is imported and used here now.
=> Fix s3 files issue

emmaa_service/api.py, emmaa_service/templates/demos_template.html, emmaa_service/templates/emmaa_page_template.html
This PR changes the link in the header from Demo to Demos, and links it to a template served from an API endpoint. The page lists demos/talks/posters related to EMMAA that can easily be extended with more content.
=> Add template for lists of demos

.github/workflows/tests.yml, doc/conf.py, doc/modules/priors.rst, emmaa/priors/literature_prior.py, emmaa_service/api.py, emmaa_service/templates/index_template.html
This PR implements a new prior module that allows initializing a model by searching for extractions from a specific subset of literature (given a list of search strings or MeSH IDs to find relevant papers). The prior class can also generate an initial config and upload the model and config to S3.
=> Implement literature prior for model initialization

emmaa/model.py, emmaa/util.py
This PR disables the storing of JSON version of raw EMMAA model and adds a delete step to pickle/json upload functions to save memory.
=> Disable JSON model storage

emmaa/util.py
This PR sets the pickle protocol to 4 when dumping pickles since EMMAA jobs are running in a Python 3.7 environment which cannot use any pickles that were dumped using protocol 5 (which is the HIGHEST_PROTOCOL in Python 3.8+).
=> Fix pickle protocol to 4

emmaa/model.py
This PR moved covid19 repo import from module level to the specific method to avoid dependency on covid19 when loading EmmaaModel
=> Import covid19 locally

emmaa/model.py, emmaa/model_tests.py, scripts/update_model_manager.py
This PR makes several changes to EmmaaModel and ModelManager:
- Updates PyBEL version in setup
- Adds `mode` parameter to EmmaaModel methods for different formats assembly, it's set to "local" by default to avoid unnecessary uploads of exports to s3 and is only set to "s3" in model manager update script run by Batch daily (in this case it will upload exported formats as configured in model config)
- Adds alternative way to load a model manager pickle from s3 - if the pickle load fails (which can happen in case of a new PyBEL or PySB version), then it loads the assembled statements instead and assembles the required model types.
=> Local mode and PyBEL versioning

emmaa/model_tests.py, emmaa/tests/test_model_tests.py
This PR goes together with https://github.com/sorgerlab/indra/pull/1216 and includes adding a new class to check applicability of tests by refinements and propagates the use of refinements in pathfinding and reporting to emmaa tests and queries. It also updates the paths JSONL format to include the type of the edge (statements, PybelEdge, RefEdge). Finally it simplifies the English assembly of reported statements by making use of INDRA `make_string_from_sort_key` function.
=> Refinements

doc/conf.py
For the time being, we need to mock out `indra.explanation.reporting` since some new INDRA code hasn't been released yet on PyPI. Doc builds seem to be passing with this.
=> Extend documentation mocks

emmaa_service/static/emmaaFunctions.js
This PR fixes a bug when pages with fewer than 10 curations were not loading due the way curation plot yticks were handled in JS.
=> Fix page load

.github/workflows/tests.yml, scripts/export_ontology.py, setup.py
This PR improves the ontology export to include MeSH root nodes that aren't part of the standard structure of MeSH.
=> Add better MeSH roots for ontology export

emmaa_service/api.py
This PR updates statement evidence page to only preload first 10 evidences if there's only one statement on the page; otherwise, display all statements without evidence and load on demand.
=> Improve statement evidence page for multiple statements

emmaa_service/api.py
This PR adds a simple endpoint to return a list of statement hashes in an EMMAA model that have been curated.
=> Add endpoint for getting curated statements in model

emmaa_service/api.py
This PR adds a suffix to the URL that links to annotations which allows them to be viewed publicly.
=> Add hypothesis group to redirect URL

emmaa_service/api.py
This PR fixes an issue when test stats for some of the test corpora are missing for the given date. Instead of using the same date for loading the statements and test stats for counting paths, it loads the latest stats available for each corpus.
=> Fix all statements bug

.github/workflows/tests.yml, doc/modules/index.rst, doc/modules/xdd.rst, emmaa/analyze_tests_results.py, emmaa/tests/test_xdd.py, emmaa/xdd/__init__.py, emmaa/xdd/xdd_client.py, emmaa_service/api.py, emmaa_service/templates/evidence_template.html, emmaa_service/templates/tabs/figures_tab.html
This PR enables retrieving figures and tables from xDD content and displaying them on EMMAA dashboard.
- xDD client that supports two main types of queries: document based (provide a paper ID of any type) and entity based (provide any agent name or comma-separated names)
- New tab on statements from paper page that shows all figures and tables extracted from that paper.
- New tab on statements evidence page that shows all figures and tables returned by querying for statement's agents names.
=> xDD integration

emmaa/model_tests.py, emmaa/tests/test_s3.py
This PR updates `model_to_tests` function to load assembled statements instead of reassembling them to create tests.
=> Model to tests

emmaa_service/api.py
This PR adds a simple endpoint for getting entity-specific info in the context of a given model. Currently it just returns an external URL, later, this can be extended to cover other universal or model-specific entity info.
=> Add entity info endpoint

emmaa_service/api.py, setup.py
This PR extends the `emmaa.api.entity_info()` function to use the Bioresolver web service to look up the name, definition, alternative provider URLs, and other metadata about the entity. It assumes the base URl for the bioresolver service is stored in the INDRA configuration such that it can be looked up with `indra.config.get_config('ENTITY_RESOLVER_URL')`
questions:
- should all metadata be returned? Currently this just updates the returned dictionary with everything from the Bioresolver's response (this includes some extra data that isn't necessary, like the success message)
- should the metadata go inside a deeper dictionary? This is more of a question on whether the logic for navigating this dictionary should be done on the frontend or pre-organized in the backend
=> Use the bioresolver to look up additional entity metadata

emmaa/analyze_tests_results.py, emmaa/filter_functions.py, emmaa/model.py, emmaa/model_tests.py, emmaa/readers/aws_reader.py, emmaa/readers/db_client_reader.py, emmaa/readers/elsevier_eidos_reader.py, emmaa/statements.py, emmaa/tests/test_filters.py, emmaa/tests/test_statements.py, scripts/emmaa_model_from_stmts.py
This PR makes the following changes:
- Adds `metadata` field to EMMAA Statement object to allow tagging statements as e.g. internal/external, literature/curated, etc.
- Propagates metadata from EMMAA Statement to the underlying INDRA Statement as annotations.
- Adds functions to filter both EMMAA and INDRA statement based on some conditions in metadata.
- Information about whether the statement is internal is propagated to edge data when assembling signed/unsigned graphs from EMMAA Model.
- Model configs allow to filter out statements from statistics based on criteria (e.g. filter out external statements from stats)
- Model-test configs allow to specify which edges should be filtered out in model checking for a given model-test corpus pair (this part depends on …
=> EMMAA Statements metadata

emmaa/model.py, emmaa/statements.py
This PR updates EmmaaModel methods for custom model updates (non-reading updates such as `update_with_cord19`, `update_from_disease_map`, and `update_from_files`). Instead of using default/hardcoded metadata, filenames, and other parameters, all information can be now provided in model config files. Loading COVID19 custom pickle files part is removed from `update_with_cord19` method, instead `update_from_files` should be used for that step with new configuration. This allows passing any custom metadata to statements loaded from a particular file or other source. This PR should be merged together with https://github.com/indralab/covid-19/pull/17
=> Configurable model updates

emmaa/statements.py, emmaa/tests/test_statements.py
This PR removes date from emmaa annotations propagated into INDRA Statements to avoid creating duplicate evidences
=> Annotations

.github/workflows/tests.yml, emmaa/analyze_tests_results.py, emmaa/model.py, emmaa/tests/test_model.py, emmaa_service/api.py
This PR fixes a couple of bugs related to tests loading in the api:
1) when there are multiple test corpora with the same prefix but the difference between them is not the date (i.e. we cannot pick one by sorting by date), e.g. covid19_curated_tests, covid19_curated_tests_c19dm.
2) when the stats are generated with refreshed hash but the test objects are stored with old hash and there's no match to load evidence (need to force hash refresh).
=> Fix test loading

emmaa/xdd/xdd_client.py
It seems like XDD service is down. This PR just catches the connection error to make sure the webpages are still loaded without figures. The XDD tests are currently failing.
=> Catch xdd connection error

doc/model_config.rst, emmaa/model.py, emmaa/tests/test_model.py
This PR enables a choice of a belief model for assembly. To switch to a different model, run reassembly step in model assembly config has to be updated. On the UI side this PR adds belief badges and an option to sort statements by belief score.
=> Belief models

emmaa_service/api.py
This PR optimizes the loading of statement evidence page by removing unnecessary loops when filtering by a list of hashes and setting a limit on number of XDD figures
=> Optimize stmt evidence page

emmaa/model.py, emmaa/tests/test_model.py
This PR adds values for junctions representing species even if their initial values are not explicitly set (i.e., they are zero).
=> Add zero initial values to Gromet export

emmaa_service/api.py
Closes #248 
This PR re-introduces lookup of information from the biolookup service if the internal bioontology doesn't provide it. This includes definition strings and species annotations.
In addition to this PR, you could change the `ENTITY_RESOLVER_URL` configuration to point to `http://biolookup.io` (though this isn't necessary since the load balancer address didn't change)
We could also consider having the EMMAA code import the `biolookup` package for getting this data directly, and possibly have it connect directly to the database instead of going through the API, though this might be a bit complicated for little gain
=> Re-introduce adding metadata from Biolookup Service

emmaa_service/static/emmaaFunctions.js
This PR makes checking of URL args more through when constructing the test corpus redirect URL (previously the redirect URL was incorrectly constructed if there were no query args in the original URL).
=> Fix test redirect URL

emmaa_service/templates/loading.html
This PR handles using loading template when the URL contains an anchor tag (by inserting the loading=true before anchor instead of the end of the URL)
=> Handle anchor when using loading template

emmaa/db/config.py, emmaa/db/constructors.py, emmaa/db/manager.py, emmaa/db/schema.py, emmaa/model.py, emmaa/model_tests.py, emmaa/tests/db_setup.py, emmaa/tests/test_answer_queries.py, emmaa/tests/test_db.py, emmaa/tests/test_notifications.py, emmaa/tests/test_s3.py, emmaa_service/api.py
This PR is aimed to offload the EMMAA service memory by loading the statements from the database instead of keeping them in memory. 
- A new statements database is created (can be set up locally on the EMMAA service machine) that allows:
- storing the statements and the corresponding path counts
- loading all statements per model/date sorted and filtered as requested (i.e. supporting all_statements page options)
- loading statements by their model/date and statement hash (i.e. supporting statement evidence pages)
- loading statements' path counts numbers (used for sorting and path badges)
- API is updated to leverage the database when the model is available; it falls back to "old" cache/filtering in memory option when the statements for model/date are not in the database
- ModelManager …
=> Use db to load statements in the API

emmaa_service/api.py, emmaa_service/templates/evidence_template.html, emmaa_service/templates/tabs/figures_tab.html
This PR changes the way figures and tables are loaded from XDD on EMMAA statement and paper pages. Instead of querying the XDD service every time the page is loaded, it will be only queried if a user clicks on a button on "Figures" tab.
=> Load figures when requested only

emmaa/statements.py, emmaa/tests/test_statements.py
This PR makes the date and search terms optional in the `EmmaaStatement` class. It better handles `None` in the related code to automatically turn them into an empty list. It also updates the tests to demonstrate this works (these tests would fail without the update)
This was necessary to get the GeneListPrior to work without modification, and ultimately makes creation of EmmaStatements safer. 
If I wanted to make a much bigger mess of the diff, I'd also consider making all of the arguments besides `stmt` to `EmmaaStatement` be keyword-only to make sure that they don't get mismatched, since a lot of places duplicate functionality by passing an empty list to `search_terms` or `datetime.datetime.now()` to `date`.
=> EMMAA statement improvements

doc/conf.py, doc/requirements.txt, emmaa/priors/gene_list_prior.py, emmaa/priors/literature_prior.py, emmaa/statements.py, emmaa/tests/test_statements.py, scripts/generate_simple_model_test.py, scripts/priors_from_muts.py
The current error I'm getting in the Pompe build on AWS Batch is because the `"internal"` key is not available in the annotations one of the EMMAA statements, which is causing the `is_internal` function to fail. This also adds a corresponding case that handles when there's a "metadata" but it's missing one of the keys needed for the conditions check -> it evaluates as false for passing the condition.
I haven't figured out where in the pipeline this annotation is supposed to be added based on the current assembly configuration yet.
=> Update undefined behavior on missing condition key

emmaa/priors/gene_list_prior.py, emmaa/priors/literature_prior.py, emmaa/statements.py
This PR does the following:
1. Reimplements `emmaa.priors.prior_stmts.get_stmts_for_gene()` to use new INDRA DB functionality
2. Adds a few extra fields to both the literature prior and the gene prior and make some fields optional via flags (but keep defaults the same as current functionality)
3. Make the `GeneListPrior.make_gene_statements()` method store the statements in the instance of the prior the same way that `LiteraturePrior.get_statements()` does
4. Makes the `LiteraturePrior.get_statements()` and  `GeneListPrior.make_gene_statements()` methods return the actual statement list after running
6. As I was grokking code, I added some type annotations and did light reformatting when that made it go over the line length limit
See results for the pompe configuration on …
=> Preparation for Pompe Disease model

.github/workflows/tests.yml, emmaa/tests/test_reactome_prior.py, emmaa/tests/test_s3.py, emmaa/util.py
This PR introduces the option to upload objects to s3, via a wrapper to `s3.put_object()`, into the intelligent tiering storage class. After merge, new uploads using any of `save_gzip_json_to_s3`, `save_json_to_s3`, or `save_pickle_to_s3` in `emmaa.util` will be put in the intelligent tiering storage class _by default_. To opt out of this storage class the caller has to specify `intelligent_tiering=False` when calling the new function `s3_put` in `emmaa.util`.
Two other functions are introduced:
- `s3_head_object`: a wrapper to `s3.head_object`
- `get_s3_archive_status`: a function returning if an object on S3 is in the intelligent tier class and if it is, if it's archived or not.
=> Intelligent tiering for new S3 uploads

emmaa/aws_lambda_functions/after_update.py
This PR adds the painmachine to the set of large models in the `after_update` lambda function defintion. This will allow the painmachine model stats, tests and test stats to be run with the job defintion in batch that has more memory, which should resolve batch jobs for the painmachine model that errored due to low memory.
After merge, run the lambda upload script:
```bash
python update_lambda.py after_update.py emmaa-after-update
```
from `emmaa/aws_lambda_functions`
=> Add painmachine to large models for after_update lambda

emmaa/util.py
This PR adds an additional condition (byte size has to be `> 128 KB`) that has to be met for setting the storage class to intelligent tiering when uploading using `s3_put`.
Some clarifications were added to two of the parameter docstrings of `s3_put` as well.
=> Check size for Intelligent Tiering

emmaa_service/api.py
This PR resolves an issue where the JavaScript in Vue receiving data to render the Vue `<statement>` component received Python `None` and `True/False` instead of JavaScript `null` and `true/false`, respectively. The solution was to make sure the data is properly json dumped as suggested here: https://stackoverflow.com/a/15322060/10478812
The code has been run locally with the same versions of Flask, Jinja2, markupsafe and werkzeug as what's running on the emmaa server and all endpoints that use the function that have been updated has been tested.
Other fixes:
- There was a namespace clash where `get_db` was imported from both `indra_db` and `emmaa`, a commit is added that fixes the clash
- A path count would sometimes be missing and a `dict.get` method would return `None` instead of a …
=> JavaScript vs Python data representation fix

emmaa/aws_lambda_functions/model_manager_update.py
~Finding no trace of outside interference that explains the nf model update jobs being killed, the assumption is that the batch job lacks enough memory to handle the model update.~
_Edit: the batch job states it doesn't have enough memory_
This PR adds nf model to the batch queue with the job definition that has more memory available to it.
After merge, the lambda function needs to be updated.
=> Include nf in large model set

.github/workflows/tests.yml, emmaa/tests/test_xdd.py, emmaa_service/api.py, setup.py
Update usage of `flask_jwt_extended` decorator to be compatible with `flask_jwt_extended>3`, which is a requirement for using `Flask>=3`.
See https://github.com/sorgerlab/indra/issues/1448.
=> Upgrade to `flask_jwt_extended>3`
