Dockerfile, buildspec.yml
Fix the docker definition by adding --no-include-email flag to aws get-login.
=> Fix the docker definition.

dashboard/emmaaFunctions.js, dashboard/index.html, dashboard/model.html
This PR updates the sourcing of javascript: awsServices.js is now loaded from [indralab.github.io](https://indralab.github.io/aws/js/awsServices.js)
=> Move js indralab github pages

dashboard/index.html, dashboard/model.html
This PR does a silent adaptation of how to set the environment for the AWS functionalities following a change in the javascript that handles those functionalities.
=> Set env before page load

.gitignore, doc/conf.py, doc/modules/readers.rst, emmaa/readers/db_client_reader.py, emmaa/tests/test_db_client_reader.py
Function that takes key-value pairs of PMIDs and search terms, checks with database, and returns list of EmmaaStatements. Also added a nosetest for it.
=> DB client reader

emmaa/model.py, emmaa/priors/__init__.py, emmaa/readers/db_client_reader.py, scripts/run_model_tests_from_s3.py, scripts/run_model_update.py
This PR fixes a few minor issues to make the model update cycle work. This now enables running scripts/run_model_update.py.
=> Bug fixes to make model update cycle work

scripts/git_and_run.sh
This PR has what seems to be a working git_and_run script to update the version of emmaa on batch without rebuilding the docker.
=> Correct git and run

scripts/get_model_test_stats.py
This PR is a script to get simple statistics about test results for each model: model name, how many tests it was run against, how many tests did it pass and fail and reasons for not passing.
=> Added script to get stats about model tests results

emmaa/model.py, emmaa/model_tests.py
This PR adds an English description of a path found in json test results on s3.
=> English test results

emmaa/model.py
This PR fixes a small bug caused by my previous PR when assembled statements were added as EmmaaModel property.
=> Fixing a bug in upload to NDEx

emmaa/analyze_tests_results.py
This PR fixes a few small bugs in StatsGenerator: appending to a list of previous data, json encoding, etc.
=> Bugs in StatsGenerator

emmaa/analyze_tests_results.py
This PR makes changes to json stats file that is used for dashboard. More detailed information about all applied tests results is added.
=> Test results update

dashboard/index.html, dashboard/model.html, dashboard/query.html
This PR makes emmaaFunctions.js be loaded  from github pages instead of from S3.
=> Switch to github pages as source for js

doc/modules/database.rst, doc/modules/index.rst, doc/requirements.txt, emmaa/db/__init__.py, emmaa/db/config.py, emmaa/db/constructors.py, emmaa/db/manager.py, emmaa/db/schema.py, emmaa/resources/default_db_config.ini, emmaa/tests/test_db.py, setup.py
This PR creates the schema and an API interface for an Emmaa database to cache queries and their results and retrieve them.
=> Emmaa Database

emmaa/model_tests.py
Fix a small bug in answer_queries method of a ModelManager. The registered queries are now being answered during test run.
=> Fix bug in answer queries

dashboard/index.html, dashboard/query.html
This PR makes two minor changes:
- Change card text: `Your previous queries` -> `Previous queries`
- Removes an outdated JS call that led to a silent error
=> Minor web changes

dashboard/query.html, dashboard/queryFunctions.js, emmaa/answer_queries.py, emmaa/model_tests.py, emmaa/tests/test_answer_queries.py, emmaa_service/test_api.py, scripts/run_model_update.py
This PR includes several improvements to queries related part of the code:
- Fixed results formatting bugs
- Fixed inconsistency in new results and db results
- Updated JS to work with standardized result format
- Added tests for answer_queries functions
- Added test for sending a query request
- Handling of lowercase agent name user input
- Updated docstrings, comments and fixed style errors
=> Queries cleanup

.travis.yml, emmaa/db/constructors.py, emmaa/tests/test_answer_queries.py, emmaa/tests/test_db.py
This PR enables using the test DB on Travis.
=> Allow DB to be tested on Travis

dashboard/emmaaFunctions.js, dashboard/index.html, dashboard/model.html, dashboard/query.html
This PR sets all relevant links to open in new tabs.
=> Open link in new tab

emmaa/readers/db_client_reader.py
This PR adapts `db_client_reader` code to the changes in `get_statements_by_paper` function introduced in https://github.com/indralab/indra_db/pull/49
=> Optimized model update

emmaa/analyze_tests_results.py
This PR makes changes to `analyze_test_results.py` by making some optimization refactoring to TestRound class (new attribute `english_test_results` is used by multiple methods and helps avoid calling the same methods multiple times), adding more comments and logs. These changes will allow more efficient running, better readability and easier debugging. The changes will not affect the way the tests are being run or the structure of test results and stats JSON files.
=> Improve stats generation code

dashboard/query.html
This PR solves the issue where different browsers showed different background colors for the query submit button.
=> Force query button background-color

dashboard/index.html, dashboard/model.html, dashboard/query.html
This PR adds a link to an introductory video to EMMAA dashboard.
=> Demo video link

emmaa/analyze_tests_results.py
This PR fixes a small bug in stats generation that was caused by updates in #97
=> Fix a bug in stats

emmaa/analyze_tests_results.py, emmaa/tests/new_results.json, emmaa/tests/previous_results.json, emmaa/tests/previous_stats.json, emmaa/tests/test_stats.py
This PR adds tests for TestRound and StatsGenerator classes needed to produce stats files that are used for dashboard. It also fixes some minor bugs in these classes methods and adds json files needed for tests.
=> Stats tests

Dockerfile, setup.py
This PR removes indralab_auth_tools from setup.py and builds it for Docker via github
=> Fix dockerbuild

emmaa/analyze_tests_results.py, emmaa/answer_queries.py, emmaa/model_tests.py, emmaa/readers/elsevier_eidos_reader.py, emmaa_service/api.py, emmaa_service/static/queryFunctions.js, emmaa_service/templates/query_template.html
Display a message when there are no new statements/applied/passed tests. Depends on change in ui_util templates.
=> Minor UI fixes

emmaa/model_tests.py
This PR is updating the process of creating strings representing paths to handle PybelEdge objects introduced in https://github.com/sorgerlab/indra/pull/1008
=> Handle display of PybelEdges

.gitignore, .travis.yml, Dockerfile, emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/db/schema.py, emmaa/model_tests.py, emmaa/queries.py, emmaa/tests/dynamic_property_query.json, emmaa/tests/test_answer_queries.py, emmaa/tests/test_api_functions.py, emmaa/tests/test_model.py, emmaa/tests/test_queries.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/static/queryFunctions.js, emmaa_service/templates/query_template.html
This PR adds a new dynamic type of queries that can be answered by running the simulation of PySB model. This PR includes both BackEnd and FrontEnd changes and installing new dependencies.
=> Dynamic queries

emmaa/aws_lambda_functions/after_update.py, emmaa/aws_lambda_functions/test_pipeline.py, emmaa/aws_lambda_functions/update_pipeline.py, emmaa/model_tests.py, emmaa/tests/test_s3.py, emmaa/util.py, emmaa_service/api.py, scripts/run_model_update.py, scripts/update_model_manager.py
This PR makes a few changes to AWS pipeline and display of results:
- Turning model into tests step is integrated (for configured models)
- Daily testing of manual models against updating tests is integrated
- List of available test corpora for dashboard is pulled from S3 results directly instead of config file
- Save to NDEx step is moved to different batch job (to reduce number of times the same model is being assembled)
=> Test updates

.travis.yml, emmaa/readers/aws_reader.py, emmaa/tests/test_lambda.py
Update imports to use `indra_reading` and add it to the Travis config.
=> Update reading imports

emmaa/model.py, emmaa/tests/test_model.py, emmaa/tests/test_s3.py
This PR adds a step in model assembly to filter out statements/update belief scores based on curations. Depends on https://github.com/sorgerlab/indra/pull/1040
=> Curations in model assembly

emmaa/tests/test_s3.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/index_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/query_template.html
This PR fixes some bugs and optimizes the run of emmaa service api.
- Getting the latest available date is only done when the model page is loaded and only for that one model (it used to be done for all models when loading index page instead)
- Some minor bugs on the query page and new added statements table are fixed
- Curated evidences are marked now at the evidence level as well
=> Corrections

emmaa_service/api.py
=> Fix a bug with a wrong variable name

emmaa/analyze_tests_results.py, scripts/update_model_manager.py
This PR updates the dependencies in stats generation process to avoid the failing batch jobs due to duplicate or missing files
=> Stats generation process

emmaa/model.py
This PR adds extra grounding steps in model assembly. They can be configured in config.json 'assembly' section.
=> Additional grounding steps in assembly

emmaa/model.py
This PR adds a function to load a custom grounding map from a json file on S3. This map can be used in model assembly to extend the default grounding map.
To trigger this, put {'grounding_map': {'policy': 'extend'}} in config['assembly'].
=> Custom grounding map

emmaa/model.py, emmaa/tests/test_model.py, emmaa/tests/test_s3.py
This PR integrates AssemblyPipeline class (https://github.com/sorgerlab/indra/pull/1079) for EMMAA models assembly. Model config files have to be updated to enable the pipeline.
=> Assemble models with pipeline

emmaa_service/static/queryFunctions.js
This PR raises an alert if a user leaves any of the required fields blank.
=> Handling empty query

emmaa_service/api.py
This PR adds model description on the model page. Service should be restarted with changes in this PR and in https://github.com/indralab/ui_util/pull/9
=> Add description on model page

.travis.yml, emmaa/priors/reactome_prior.py, emmaa/queries.py, emmaa/tests/test_queries.py, emmaa/tests/test_reactome_prior.py
This PR should be merged after sorgerlab/indra#1100 to adapt a standardization step to the ontology graph approach.
=> Ontology graph

emmaa/readers/db_client_reader.py
This PR changes the call to INDRA DB using the recommended function instead of deprecated.
=> Update database function call

.travis.yml, Dockerfile, emmaa/analyze_tests_results.py, emmaa/model.py, emmaa/model_tests.py, emmaa/util.py, emmaa_service/api.py, scripts/emmaa_model_from_stmts.py
This PR adds a method in EmmaaModel that allows getting statements from CORD19 corpus and combine them with existing model statements, gordon statements and drug statements. Note that this method doesn't just add new statements but overwrites the existing statements with new ones (date and search terms are also overwritten). This PR also installs covid_19 repo in emmaa docker.
=> CORD19 update

emmaa/answer_queries.py, emmaa/db/manager.py, emmaa/model.py, emmaa/model_tests.py, emmaa/queries.py, emmaa/tests/open_query.json, emmaa/tests/test_answer_queries.py, emmaa/tests/test_queries.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/static/queryFunctions.js, emmaa_service/templates/email_unsub/email_body.html, emmaa_service/templates/query_template.html
This PR implements new type of queries - open search queries (upstream or downstream of a given node). This PR depends on https://github.com/sorgerlab/indra/pull/1157
=> Open queries

emmaa_service/api.py
This PR fixes a bug introduced in #175 by making sure the requirement to add links is specified in stats.
=> Fix links bug

emmaa/model.py, emmaa/model_tests.py, emmaa/util.py, emmaa_service/api.py, emmaa_service/templates/model_template.html
This PR adds model exports during assembly for a set of configured export formats for each model. The dashboard then displays links to each export's latest version.
=> Generate model exports and add download links

.github/workflows/tests.yml, emmaa/tests/test_queries.py, scripts/export_ontology.py, scripts/export_url_patterns.py, setup.py
This PR adds to scripts to create custom exports for integration with a UI:
- a dump of relevant URL patterns for a model
- a custom bio ontology export that makes customizations to its structure
=> Add scripts for custom exports for UI integration

emmaa/analyze_tests_results.py, emmaa/tests/test_stats.py
This PR is a follow up to the #172 and propagates the paper statistics into tweet messages.
=> Tweet papers

emmaa/tests/test_queries.py
This PR updates MeSH IDs assigned to some proteins during grounding standardization.
=> Update grounding in tests

emmaa/analyze_tests_results.py, emmaa/model_tests.py, emmaa/tests/previous_model_stats.json, emmaa/tests/test_s3.py, emmaa/tests/test_stats.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/evidence_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/query_template.html, emmaa_service/templates/tabs/curation_tab.html, emmaa_service/templates/tabs/dynamic_query_tab.html, emmaa_service/templates/tabs/model_tab.html, emmaa_service/templates/tabs/open_query_tab.html, emmaa_service/templates/tabs/paper_tab.html, emmaa_service/templates/tabs/static_query_tab.html, emmaa_service/templates/tabs/tests_tab.html
This PR adds code to generate relevant statistics and build UI for new paper and curation tabs on EMMAA dashboard. HTML templates are refactored to have each tab in a separate file for better readability.
=> Paper and Curation tabs

emmaa/model_tests.py, emmaa/tests/test_model_tests.py
A small update to go along with https://github.com/sorgerlab/indra/pull/1214
=> Update handling of output from group_and_sort function.

emmaa_service/api.py
This PR adds several new endpoints to EMMAA API to retrieve information about models and tests
=> New endpoints

emmaa/answer_queries.py, emmaa/model_tests.py, emmaa_service/api.py
This PR adds an endpoint to run queries programmatically. To run a query, one has to pass a query json and a model name as parameters.
=> Queries API

scripts/export_ontology.py
This PR extends the ontology export script with new categories.
=> Extend ontology export script

emmaa/analyze_tests_results.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js
This PR adds a new endpoint for uploading annotations to hypothes.is for a given paper and front end support to do it from EMMAA dashboard. It also reformats   generating links to publications process and changes the priority of text ref IDs for this task (PMICD, PMID, DOI). This PR goes together with https://github.com/sorgerlab/indra/pull/1237 and https://github.com/indralab/ui_util/pull/15
=> Hypothesis annotation

emmaa_service/api.py
This PR sorts the statements on the statement evidence page by evidence count.
=> Sort statements

.github/workflows/tests.yml, emmaa/model.py, setup.py
This PR creates new methods in EmmaaModel that allow getting model statements from MINERVA disease maps and custom files.
=> Disease map

emmaa/analyze_tests_results.py
Fix the error when there are no applied tests
=> Fix division by zero

emmaa/model.py
This PR updates EmmaaModel method to overwrite existing statements instead of extending it when the statements are sourced not from reading (e.g. from disease map, custom pickle files, custom script, etc.) to avoid conflicts.
=> Overwrite existing statements

emmaa_service/templates/tabs/model_tab.html
This PR updates model tab template to move some of the html from ui_util (https://github.com/indralab/ui_util/pull/17) and adds a chat button directly on model page.
=> Chat button and update html

emmaa/aws_lambda_functions/after_update.py, emmaa/model_tests.py, emmaa/statements.py, emmaa/tests/test_model.py, emmaa/tests/test_s3.py
Main change in this PR is to apply filters when creating model tests. In addition, it makes small changes to EmmaaStatement and relevant tests.
=> Model tests

doc/index.rst, doc/model_config.rst, doc/modules/filters.rst, doc/modules/index.rst, doc/modules/priors.rst, doc/modules/readers.rst, emmaa/model_tests.py
This PR adds a documentation for creating model config files.
=> Model config docs

.github/workflows/tests.yml, Dockerfile, emmaa/model.py
This PR installs indra_world in EMMAA docker and tests and imports it inside `run_assembly` function to make sure Food Insecurity model's pipeline works
=> Use indra_world in EMMAA

doc/model_config.rst, emmaa/answer_queries.py, emmaa/db/schema.py, emmaa/model_tests.py, emmaa/queries.py, emmaa/tests/intervention_query.json, emmaa/tests/test_answer_queries.py, emmaa/tests/test_queries.py, emmaa_service/api.py, emmaa_service/static/queryFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/query_template.html, emmaa_service/templates/tabs/dynamic_query_tab.html, emmaa_service/templates/tabs/open_query_tab.html, emmaa_service/templates/tabs/static_query_tab.html, emmaa_service/test_api.py
This PR introduces new Query type that allows to simulate intervention effects. In addition, some simplifications/generalizations across query tabs are done to query page code.
=> Source-target dynamics queries

Dockerfile
Fix the install of indra_db[misc]
=> Install extras_require in docker

emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/evidence_template.html
This PR adds:
- belief badges to all views of the statements
- sorting by belief option in all statements page
- filter by statement type in all statements page
- link from statement type distribution plot bars to all statements view filtered to relevant statement type
=> All statements filters and sorts

emmaa/analyze_tests_results.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/emmaa_page_template.html, emmaa_service/templates/evidence_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/tabs/belief_tab.html
This PR adds belief tab on model page, adds filtering by belief on all_statements page and adds beliefs to model stats.
=> Belief stats and UI

emmaa/model.py
This PR handles GroMEt errors when assembling the model graphs to avoid the assembly jobs failing
=> Gromet error

emmaa/statements.py
This PR applies fix_invalidities to all new statements before wrapping into EMMAA statements
=> Fix new invalid statements

emmaa_service/api.py
This PR implements a native name/url/description lookup independent of bioresolver, at least temporarily.
=> Implement native entity lookup

emmaa/analyze_tests_results.py, emmaa/tests/test_stats.py, emmaa_service/api.py, emmaa_service/static/emmaaFunctions.js, emmaa_service/templates/evidence_template.html, emmaa_service/templates/model_template.html, emmaa_service/templates/tabs/agent_tab.html, emmaa_service/templates/tabs/tests_tab.html
This PR adds:
- Class for generating statistics for a given entity in the model
- New tab on the dashboard displaying agent level stats
- New filter (by agent) on all statements page
=> Agent view

emmaa/xdd/xdd_client.py
Update XDD document search URL
=> Fix XDD error

doc/model_config.rst, emmaa/model.py
Add an option to configure a different indranet assembly method in config
=> Configure indranet method in model config

emmaa/priors/prior_stmts.py
This reimplements `get_stmts_for_gene()` using non-deprecated code from the principal database client (the old implementation no longer works).
=> Reimplement `get_stmts_for_gene()`

emmaa_service/static/widget/css/app.css
This PR updates the CSS to change the style for the Clare and user chat bubbles.
=> Update chat bubble styles

.github/workflows/tests.yml, emmaa/model.py, emmaa/tests/test_model.py
This PR:
1. Comments out the gromet installation from the test setup
2. Raises an error if the only function using GroMEt is called
3. Add a skip tag to the test that tests the GroMEt export
4. Ensures GroMEt is not allowed as model export format
=> Gromet fix

emmaa/model_tests.py
This PR caches model entity name sets so that they don't have to be calculated over and over which turns out to be very slow for large models.
=> Optimize entity name getting
